
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cakuykyvenzuntlifsni.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNha3V5a3l2ZW56dW50bGlmc25pIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQyMDQzNTQsImV4cCI6MjA1OTc4MDM1NH0.2_pGwpF5f-h3iAhKN0E4vd_U-hphx1MWxw-LxPjMVAY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(
  SUPABASE_URL, 
  SUPABASE_PUBLISHABLE_KEY,
  {
    auth: {
      persistSession: true,
      autoRefreshToken: true,
      storageKey: 'erpUser'
    }
  }
);
